spring:
    ##Druid##

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/study_redis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: "000000"
      driver-class-name: com.mysql.jdbc.Driver
      min-idle: 5
      max-active: 100
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true
      filters: stat
  redis:
#  数据库索引
    database: 0
    host: localhost
    port: 6379
    password:
#    连接最大的连接数
    pool:
      max-active: 8
#      连接池的阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
#      连接池中的最大空闲连接
      max-idle: 8
#      连接池中的最小空闲连接
      min-idle: 0
#      连接超时(毫秒)
    timeout: 0

mybatis:
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
logging:
  level: debug